"""
Globale Konfigurationen für die HMI-Anwendung.
"""

# Window Configuration
MAIN_WINDOW_WIDTH = 1400
MAIN_WINDOW_HEIGHT = 850
MAIN_WINDOW_TITLE = "HyGeNa HMI - Professional Demo Application"

# Sidebar Configuration
SIDEBAR_WIDTH = 90
SIDEBAR_BG_COLOR = "#2b3e50"
SIDEBAR_ICON_COLOR = "#b0b7c3"
SIDEBAR_ACTIVE_COLOR = "#3498db"

# Header/Footer Configuration
HEADER_FOOTER_HEIGHT = 70

# Content Container
CONTENT_AREA_BG_COLOR = "#ecf0f1"
CONTENT_CONTAINER_BG_COLOR = "#ffffff"
CONTENT_CONTAINER_PADDING = 20
CONTENT_CONTAINER_RADIUS = 8

# Colors
PRIMARY_COLOR = "#3498db"
DANGER_COLOR = "#e74c3c"
SUCCESS_COLOR = "#2ecc71"
WARNING_COLOR = "#f39c12"
TEXT_PRIMARY = "#2c3e50"
TEXT_SECONDARY = "#7f8c8d"
BG_PRIMARY = "#ecf0f1"
BG_SECONDARY = "#ffffff"

# Typography
FONT_SIZE_BODY = 11
FONT_SIZE_HEADER = 14
FONT_SIZE_TITLE = 16
FONT_SIZE_SMALL = 9

# Simulation Window
SIMULATION_WINDOW_WIDTH = 600
SIMULATION_WINDOW_HEIGHT = 800
SIMULATION_WINDOW_TITLE = "Simulation & Control Panel"

# Default Plant State Values
DEFAULT_TEMPERATURE = 20.0
DEFAULT_PRESSURE = 1.0
DEFAULT_FILL_LEVEL = 50.0
DEFAULT_PUMP_STATUS = False
DEFAULT_SYSTEM_STATE = "STOPPED"  # STOPPED, RUNNING, EMERGENCY_STOP
